services:
  # Postgres Service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: "nestjs"
      POSTGRES_DB: nestjs
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Service
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  postgres_data:
  redisdata:
    driver: "local"
