"use client";

import { Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DialogClose,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

export function AuthenticatorSuccessDialog() {
  return (
    <>
      <DialogHeader className="space-y-4">
        <DialogTitle className="flex items-center space-x-2">
          <Check className="h-6 w-6 text-green-500" />
          <span>Authenticator app successfully added</span>
        </DialogTitle>
        <DialogDescription>
          From now on, whenever you sign in to your account, you&apos;ll need to
          enter both your password and also an authentication code generated by
          your authenticator app.
        </DialogDescription>
      </DialogHeader>
      <DialogFooter>
        <DialogClose asChild>
          <Button type="button">Done</Button>
        </DialogClose>
      </DialogFooter>
    </>
  );
}
