"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";

import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormMessage,
} from "@/components/ui/form";
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSeparator,
  InputOTPSlot,
} from "@/components/ui/input-otp";
import { useEffect, useState } from "react";

const MAX_LENGTH = 6;
const FormSchema = z.object({
  pin: z.string().min(MAX_LENGTH, {
    message: `Your one-time password must be ${MAX_LENGTH} characters.`,
  }),
});

export default function TotpLogin() {
  const form = useForm<z.infer<typeof FormSchema>>({
    resolver: zodResolver(FormSchema),
    defaultValues: {
      pin: "",
    },
  });

  const pin = form.watch("pin");
  const [submitted, setSubmitted] = useState(false);

  useEffect(() => {
    if (pin.length === MAX_LENGTH && !submitted) {
      setSubmitted(true);
      form.handleSubmit(onSubmit)();
    }
  }, [pin, submitted, form]);

  function onSubmit(data: z.infer<typeof FormSchema>) {
    console.log("submit", data);
  }

  return (
    <div>
      <h1 className="text-center text-2xl font-semibold tracking-tight mb-6">
        Log in using your authenticator app
      </h1>
      <p className="text-center text-gray-400">
        To continue, please enter the 6-digit verification code generated by
        your authenticator app.
      </p>
      <div className="flex items-center justify-center">
        <Form {...form}>
          <form
            onSubmit={form.handleSubmit(onSubmit)}
            className="space-y-6 text-center mt-4"
          >
            <FormField
              control={form.control}
              name="pin"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <InputOTP maxLength={6} {...field} autoFocus>
                      <InputOTPGroup>
                        <InputOTPSlot index={0} />
                        <InputOTPSlot index={1} />
                        <InputOTPSlot index={2} />
                      </InputOTPGroup>
                      <InputOTPSeparator />
                      <InputOTPGroup>
                        <InputOTPSlot index={3} />
                        <InputOTPSlot index={4} />
                        <InputOTPSlot index={5} />
                      </InputOTPGroup>
                    </InputOTP>
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <Button type="submit" className="w-full">
              Submit
            </Button>
          </form>
        </Form>
      </div>
    </div>
  );
}
